name: Build and Push Docker Image to Docker Hub and ECR

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Specify the ECR repository name
  ECR_REPOSITORY: public.ecr.aws/us-east-1/dc-gha-ecr-repo
  
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ LATEST }} .
      
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ LATEST }}

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Tag Docker image for ECR
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ LATEST }} ${{ secrets.AWS_ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ LATEST }}
      
      - name: Push Docker image to Amazon ECR
        run: docker push public.ecr.aws/us-east-1/dc-gha-ecr-repo:${{ LATEST }}

        
      - name: Trigger Terraform Workflow
        if: success()
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/dcolanderjr/vpc-terraform-github-actions/actions/workflows/terraform.yml/dispatches \
            -d '{"ref": "main"}'
